site_name: RUNN (Random Utility Neural Network)
nav:
  - Home: index.md
  - Installation: installation.md
  - Examples: [] # this will be filled in automatically to include reference to all the notebooks
  - Contributing: contributing.md
  - Changelog: CHANGELOG.md
  - Reference: []
theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.indexes
repo_url: https://github.com/JoseAngelMartinB/runn/
site_dir: .docs
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tasklist:
      clickable_checkbox: true
  - toc:
      permalink: "#"
      toc_depth: 3
hooks:
  - docs/static/hooks.py
plugins:
  - autorefs
  - mkdocs-jupyter:
      include: ["examples/*.ipynb"]
      allow_errors: false
      kernel_name: runn
      include_source: True
      execute: false
  - search
watch:
  - runn
extra_css:
  - static/extras.css
extra:
  version:
    provider: mike