name: Build Package

on:
  push:
    tags:
      - 'v*'

jobs:
  conda-build:
    uses: JoseAngelMartinB/github_actions/.github/workflows/conda-build.yml@main
    secrets:
      ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
    with:
      package_name: runn